In [1]:
import pandas as pd

df = pd.read_csv("chembl_hia_raw_from_api.csv")

df.shape

(35437, 9)

In [2]:
df['standard_type'].value_counts()

standard_type
Papp                        17950
permeability                15235
logPapp                       916
Permeability                  564
Papp A to B (mean)            274
Drugabsorption                191
Absorption                    144
LogPapp                        38
Permeability coefficient       37
Caco-2 Papp                    34
Pcaco2                         14
Cell permeation                13
Papp e-6                        8
Papps                           7
Caco-2 permeability             4
Permeability rate               4
Caco-2 A-B                      3
PCaco-2                         1
Name: count, dtype: int64

In [3]:
df['standard_units'].value_counts()

standard_units
10'-6 cm/s    8562
10^-6 cm/s    8010
ucm/s         6812
nm/s          6118
%             1168
              ...
10'-9cm/s        1
microg/cm3       1
cm2/sec          1
uL/min.mg        1
ml/hr/kg         1
Name: count, Length: 106, dtype: int64

In [4]:
df_papp = df[
    df['standard_type'].str.lower().str.contains("papp", na=False)
]

df_perm = df[
    df['standard_type'].str.lower().str.contains("permeability", na=False)
]

In [8]:
df_papp.shape

(19227, 9)

In [9]:
df_perm.shape

(15844, 9)

In [10]:
df_papp['standard_units'].value_counts()

standard_units
10^-6 cm/s          4790
10'-6 cm/s          4553
ucm/s               4240
nm/s                2773
1E-6 cm/s            244
cm s-1               184
10'6cm/s             183
cm/s * 10E6          119
10'-7 cm/s           112
cm/s                 101
10'-5cm/s             91
uL/hr/cm2             70
10'-5 cm/s            64
10^6cm/s              63
nM/s                  61
10^-8cm/s             54
10'-4 cm/s            51
10^7cm/s              50
10^-7 cm/s            45
10^-5cm/s             43
%                     37
10E-6 cm/s            30
10'-6/cm              26
nm s-1                25
10e-6 cm s-1          23
10'-8cm/s             20
10'-6nanometer/s      16
10'-6cm/min           11
10'-2 cm/s            11
10-6 cm/s             11
10'-6cm/s              9
cm min-1               8
10'-6cm/s2             8
10^-5 cm/s             7
umol/L/s               6
ucm                    6
um/s                   5
10'-3cm/min            4
10^-6/cm               4
10'-8m/s               4
cm'-6/s                4
nM s-1                 4
10-6 cm s-1            3
10^-5 cm/min           3
nmol/sec               3
10'-6cm                2
10'-6m/s               2
uM                     2
10^-6cm2/s             1
10'-6/s                1
10'-3cm/s              1
uL/min.mg              1
10'-9cm/s              1
microg/cm3             1
microg/cm2             1
nanometer/sec          1
cm2/sec                1
Name: count, dtype: int64

In [11]:
df_perm['standard_units'].value_counts()

standard_units
10'-6 cm/s     4009
nm/s           3345
10^-6 cm/s     3220
ucm/s          2572
%               838
               ...
ug/cm2.hr         1
10^-6cm/min       1
10'-6/s           1
nmol/sec          1
10^-6m/s          1
Name: count, Length: 71, dtype: int64

In [12]:
df['standard_units'] = (
    df['standard_units']
    .astype(str)
    .str.lower()
    .str.strip()
)

In [13]:
unit_map = {
    "10'-6 cm/s": "1e-6 cm/s",
    "10^-6 cm/s": "1e-6 cm/s",
    "10e-6 cm/s": "1e-6 cm/s",
    "10e-6 cm s-1": "1e-6 cm/s",
    "1e-6 cm/s": "1e-6 cm/s",
    "10-6 cm/s": "1e-6 cm/s"
}

In [14]:
df['unit_normalized'] = df['standard_units'].replace(unit_map)

In [15]:
df['unit_normalized'].value_counts().head(20)

unit_normalized
1e-6 cm/s      16880
ucm/s           6812
nm/s            6282
%               1168
nan             1129
nm s-1           453
10'6cm/s         370
10'-7 cm/s       290
cm s-1           271
cm/s             200
10'-5 cm/s       126
cm/s * 10e6      119
10'-5cm/s        110
10'-4 cm/s       106
ul/hr/cm2         92
10^6cm/s          89
10^-7 cm/s        86
10^-8cm/s         55
10^-5cm/s         51
10^7cm/s          50
Name: count, dtype: int64

In [16]:
df[df['unit_normalized'] == 'ucm/s'][['standard_type', 'value']].head(10)

    standard_type  value
355          Papp  35.00
356          Papp  42.00
358          Papp   2.66
359          Papp  16.81
360          Papp   4.56
361          Papp   4.93
362          Papp   7.21
363          Papp   3.82
364          Papp   5.61
365          Papp   1.50

In [17]:
df[df['unit_normalized'] == 'nm/s'][['standard_type', 'value']].head(10)

    standard_type  value
313          Papp  470.0
314          Papp   14.0
315          Papp  150.0
316          Papp   69.0
317          Papp  140.0
340          Papp   50.0
341          Papp   50.0
342          Papp   50.0
343          Papp   50.0
344          Papp   50.0

In [18]:
df_core = df[df['unit_normalized'] == '1e-6 cm/s']

In [19]:
df_core.shape

(16880, 10)

In [20]:
df_core.to_csv(
    r"C:\Users\kiran\Cheminformatics_course\New_Project\Absorption\Data_set\core_papp_dataset_16000.csv",
    index=False
)

In [23]:
df.columns

Index(['assay_chembl_id', 'canonical_smiles', 'molecule_chembl_id',
       'standard_type', 'standard_units', 'standard_value', 'type', 'units',
       'value', 'unit_normalized'],
      dtype='object')

In [24]:
df[df['unit_normalized'] == '1e-6 cm/s'][
    ['standard_type', 'standard_value']
].head(50)

    standard_type  standard_value
96           Papp            2.10
97           Papp            0.20
98           Papp            0.20
99           Papp            0.10
100          Papp            0.30
101          Papp            2.20
102          Papp            0.10
103          Papp            0.10
104          Papp            0.70
105          Papp            0.20
106          Papp            0.20
137          Papp            5.88
138          Papp           20.50
139          Papp            4.97
162          Papp           36.00
163          Papp           18.00
164          Papp           14.00
165          Papp            6.00
166          Papp           36.00
167          Papp           10.00
168          Papp           11.00
169          Papp            5.00
170          Papp           35.00
689          Papp            0.02
690          Papp            0.70
691          Papp            0.44
692          Papp            2.65
693          Papp            1.70
694          Papp            3.00
695          Papp            3.00
696          Papp            0.25
697          Papp            3.40
698          Papp            4.49
699          Papp            1.92
700          Papp            5.25
701          Papp            5.50
702          Papp            2.68
703          Papp           11.86
704          Papp           16.52
705          Papp           16.69
706          Papp           17.24
707          Papp           19.06
708          Papp           15.74
709          Papp            9.39
710          Papp            2.85
711          Papp            4.52
712          Papp           11.71
713          Papp           10.78
714          Papp            5.21
715          Papp           12.42

In [25]:
df[df['unit_normalized'] == 'ucm/s'][
    ['standard_type', 'standard_value']
].head(50)

    standard_type  standard_value
355          Papp           35.00
356          Papp           42.00
358          Papp            2.66
359          Papp           16.81
360          Papp            4.56
361          Papp            4.93
362          Papp            7.21
363          Papp            3.82
364          Papp            5.61
365          Papp            1.50
366          Papp            4.93
367          Papp            4.45
368          Papp            5.00
369          Papp           32.00
370          Papp            3.00
371          Papp            4.60
372          Papp           34.00
373          Papp           18.00
374          Papp            7.39
375          Papp            6.56
376          Papp           36.30
414          Papp            1.94
415          Papp            0.33
471          Papp            2.20
480          Papp            6.60
481          Papp            9.40
482          Papp           25.70
483          Papp            0.10
484          Papp           16.30
485          Papp           14.70
486          Papp           21.60
487          Papp            3.40
488          Papp           13.50
489          Papp           12.50
490          Papp           14.60
491          Papp           25.00
504          Papp           20.00
505          Papp            9.00
506          Papp           83.00
507          Papp            3.60
508          Papp            0.80
509          Papp            0.56
510          Papp            0.79
511          Papp            0.88
512          Papp            0.20
513          Papp            0.10
514          Papp            0.10
515          Papp            0.55
516          Papp            0.55
517          Papp            0.81

In [26]:
df['unit_normalized'] = df['unit_normalized'].replace({
    'ucm/s': '1e-6 cm/s'
})

In [27]:
df['unit_normalized'].value_counts().head()

unit_normalized
1e-6 cm/s    23692
nm/s          6282
%             1168
nan           1129
nm s-1         453
Name: count, dtype: int64

In [28]:
df_23000 = df[df['unit_normalized'] == '1e-6 cm/s']

In [31]:
df_23000.to_csv(
    r"C:\Users\kiran\Cheminformatics_course\New_Project\Absorption\Data_set\mixed_ucm_papp_dataset_23000.csv",
    index=False
)